// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistencia;

namespace paginaprueba1.app.Migrations
{
    [DbContext(typeof(appContext))]
    [Migration("20221001015917_InitialDbMigration")]
    partial class InitialDbMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dominio.AgendaCitas", b =>
                {
                    b.Property<int>("idAgendaCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("fechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("idMascota")
                        .HasColumnType("int");

                    b.Property<int>("idVeterinario")
                        .HasColumnType("int");

                    b.HasKey("idAgendaCita");

                    b.ToTable("citas");

                    b.HasData(
                        new
                        {
                            idAgendaCita = 1,
                            fechaHora = new DateTime(2022, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            idMascota = 1,
                            idVeterinario = 1
                        });
                });

            modelBuilder.Entity("Dominio.AsistenteVeterinaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("docResponsable")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("docVeterinaria")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("nombreResponsable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("telefono")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("asistentes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            docResponsable = 1001256489m,
                            docVeterinaria = 1m,
                            nombreResponsable = "Karen Daniela Ochoa Vasquez",
                            telefono = 3164586231L
                        });
                });

            modelBuilder.Entity("Dominio.Mascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("docDueño")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("edadMascota")
                        .HasColumnType("int");

                    b.Property<string>("nombreMascota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("raza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoMascota")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("mascotas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            docDueño = 1016526325m,
                            edadMascota = 8,
                            nombreMascota = "verano",
                            raza = "Labrador",
                            tipoMascota = "Perro"
                        });
                });

            modelBuilder.Entity("Dominio.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("documento")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("nombreCompleto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("perfil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("telefono")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("personas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            contraseña = "callefalsa123",
                            correo = "vet.mundoanimal@gmail.com",
                            documento = 1m,
                            nombreCompleto = "Veterinaria Mundo Animal",
                            perfil = "admin",
                            telefono = 3194482143L
                        },
                        new
                        {
                            Id = 2,
                            contraseña = "1234",
                            correo = "jorge_36@gmail.com",
                            documento = 4651289m,
                            nombreCompleto = "Jorge Hernandez Cruz",
                            perfil = "vet",
                            telefono = 3102568465L
                        },
                        new
                        {
                            Id = 3,
                            contraseña = "1234",
                            correo = "julianat@gmail.com",
                            documento = 1016526325m,
                            nombreCompleto = "Juliana Torres Arango",
                            perfil = "client",
                            telefono = 3205641523L
                        });
                });

            modelBuilder.Entity("Dominio.Veterinario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("docVeterinario")
                        .HasColumnType("bigint");

                    b.Property<long>("numMatriProfesional")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("veterinarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            docVeterinario = 4651289L,
                            numMatriProfesional = 1001256L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
